# Exercise 3.1: Prime numbers

**a)** Write a function that tests if a number is prime. Test your function on several simple examples of prime and nonprime numbers, e.g. 17, 28, 131, 1573.

In [20]:
# write your code here

def is_prime(n):
    for i in range(2,int(n/2)+1): # there are no factors of n larger than n/2  
        if n%i == 0:
            return False
    return True


In [21]:
tests = [17,28,131,1573]

for n in tests:
    if is_prime(n):
        print(f"{n} is a prime.")
    else:
        print(f"{n} is not a prime.")

17 is a prime.
28 is not a prime.
131 is a prime.
1573 is not a prime.


**b)** To assess the efficiency of your implementationt, it is useful to measure how much time your code takes to run. In Jupyter, you can do it using [IPython magic](https://ipython.readthedocs.io/en/stable/interactive/magics.html) ``%%timeit``. This command will run the cell several times and give you the average time that your code took. Choose several large numbers, e.g. 479001599 and 526891377, and check how much it takes to check if these numbers are prime using your function from task (a). Do you have any ideas how to make your function more efficient?

In [22]:
%%timeit 

# write your code here

is_prime(479001599)

13.9 s ± 66.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [23]:
%%timeit 

# write your code here

is_prime(526891377)

372 ns ± 1.13 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


To make your function more efficient, you can notice that any nonprime number $n$ has a factor not larger than $\sqrt{n}$. Therefore, it is enough to run the cycle in your function until $\sqrt{n}$ instead of $n/2$. Let us try changing the function this way and time it again:

In [2]:
from math import sqrt 

def is_prime_2(n):
    for i in range(2,int(sqrt(n))+1): 
        if n%i == 0:
            return False
    return True

In [4]:
%%timeit 

is_prime_2(479001599)

1.18 ms ± 3.99 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
%%timeit 

is_prime_2(526891377)

389 ns ± 2.69 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


You can see that now the function runs much faster on large prime numbers!

**c)** Write a function that returns *factorization* of an integer $n$, i.e. all the prime factors and their multiplicities, as a dictionary. Test your function on several numbers, e.g. 17, 28, 131, 1573. Time your function on some larger prime and nonprime numbers, e.g. 15793 (nonprime), 15797 (prime), 526891377 (nonprime), 479001599 (prime). This may take some time. Do you have any ideas how to make your function more efficient?

**Comment**: To compare efficiency, here we will write two functions: ``factorize_1`` and ``factorize_2``. The only difference between them is that ``factorize_1`` uses a *for* loop and ``factorize_2`` uses a *while* loop from $2$ to $n/2$. 

Timing both functions, we see that ``factorize_2`` runs much faster than ``factorize_1`` on large nonprime numbers. This is due to the fact that the *for* loop defines the iterator only once using the initial (large) value of $n$, so even as $n$ decreases inside the loop, the iterator does not change. Therefore, ``factorize_1`` always runs $n/2-1$ iterations. On the other hand, the *while* loop in ``factorize_2`` compares the current values of $i$ and $n$ in every iteration, so it will run fewer iterations if $n$ is not a prime. 

On the other hand, ``factorize_2`` is slower than ``factorize_1`` on prime numbers. This is because both functions need to run $n/2-1$ iterations for a prime $n$ but the *while* loops is slower than the *for* loop.

In [24]:
# write your code here

def factorize_1(n):
    factors = dict()
    
    
    for i in range(2,int(n/2)+1):
        if n%i == 0:
            factors[i] = 1
            n = n/i
        while n%i == 0:
            n = n/i
            factors[i] += 1
     
    if bool(factors) is False: # checks if the dictrionary is empty
        factors[n] = 1
        
    return factors


def factorize_2(n):
    factors = dict()
    
    i = 2
    while i <= n/2+1:
        if n%i == 0:
            factors[i] = 1
            n = n/i
        while n%i == 0:
            n = n/i
            factors[i] += 1
        i += 1
     
    if bool(factors) is False: # checks if the dictrionary is empty
        factors[n] = 1
        
    return factors
            

In [25]:
%%timeit

factorize_1(15793) # nonprime number

912 µs ± 8.62 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [26]:
%%timeit

factorize_2(15793) # nonprime number

93.6 µs ± 398 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [27]:
%%timeit

factorize_1(15797) # prime number

896 µs ± 3.63 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [28]:
%%timeit

factorize_2(15797) # prime number

1.51 ms ± 6.93 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [29]:
%%timeit

factorize_1(526891377) # large nonprime number

31.4 s ± 119 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [30]:
%%timeit

factorize_2(526891377) # large nonprime number

563 µs ± 1.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [31]:
%%timeit

factorize_1(479001599) # large prime number

28.4 s ± 119 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [32]:
%%timeit

factorize_2(479001599) # large prime number

47.3 s ± 145 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Exercise 3.2: Let's Make a Deal!



<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Monty_open_door.svg/2880px-Monty_open_door.svg.png" alt="Monty Hall" width="500"/>

**a)** Write a text-based game that simulates the famous [Monty Hall problem](https://en.wikipedia.org/wiki/Monty_Hall_problem): 

<br />
<center>
The player is on a show and given the choice of three doors: Behind one door is a car; behind the others, goats. The player picks a door, say No. 1, and the host, who knows what's behind the doors, opens another door, say No. 3, which has a goat. He then says to the player, "Do you want to pick door No. 2?" (i.e. switch the choice) The player answers "Yes" or "No". The host opens the door of choice and reveals if the player won or lost the game.

</center>

Use ``random.choice()`` function of ``random`` module to choose a random integer out of a set. Use in-built Python method ``input()`` to record player's responses. 

In [11]:
# write your code here
import random


def monthy_hall(start_choice=None, change_choice=None, verbose=True):
    '''Simulation of the Monty Hall problem. 
    
    start_choice: If None, the player is asked to choose a door at the start of the game (as input). If start_choice is in [1,2,3], it specifies the initial door choice.
                  
    change_choice: If None, the player is asked if they want to change the choice or not (as input). If change_choice is in ['yes','no'], it specifies whether the player changes the choice after the host opens a door.
                  
    verbose: If True, the conversation between the player and the host is printed. If False, the game runs silently.
    
    '''
    
    all_doors = set([1,2,3])
    
    car = random.choice(list(all_doors))
    
    if start_choice is None:
        
        if verbose is True:
            print('HOST: Guess which door has the car behind! You can type 1, 2 or 3.\n')
            print("........\n")
        choice = int(input())
        while choice not in all_doors:
            if verbose is True:
                print('HOST: There is no such a door! Choose 1, 2 or 3.\n')
            choice = int(input())
        if verbose is True:
            print(f'HOST: You chose door {choice}!\n')
            print("........\n")
    else:
        choice = start_choice
        
    door_with_goats = all_doors - set([car])
    door_to_open = random.choice(list(door_with_goats - set([choice])))
    door_left = list(all_doors - set([choice]) - set([door_to_open])).pop()
    
    if verbose is True:
        print(f"*The host opens door {door_to_open}*\nHOST: There is a goat behind door {door_to_open}!\n")
        print("........\n")
        
    if change_choice is None:
        if verbose is True:
            print(f"HOST: Do you want to change your choice from door {choice} to door {door_left}? You can type 'yes' or 'no'.\n")
            print("........\n")
        change = input()
    else:
        change = change_choice
    
    if change == 'yes':
        choice = door_left
            
    if verbose is True:            
        print(f"HOST: Your final choice is door {choice}!\n")
        print("........\n")
    
    if choice == car:
        if verbose is True:
            print("YOU WON!")
            print("........\n")
        return 1
    else:
        if verbose is True:
            print("YOU LOST!")
            print("........\n")
        return 0
    
        
    return start_choice


**Comment:** The text in '''...''' at the beginning of the function (right after the definition) is the documentation, which you can access as ```?monthy_hall``` or ```help(monthy_hall)```.

In [13]:
?monthy_hall

In [34]:
monthy_hall()

HOST: Guess which door has the car behind! You can type 1, 2 or 3.

........

1
HOST: You chose door 1!

........

*The host opens door 3*
HOST: There is a goat behind door 3!

........

HOST: Do you want to change your choice from door 1 to door 2? You can type 'yes' or 'no'.

........

yes
HOST: Your final choice is door 2!

........

YOU WON!
........



1

**b)** Run two following scenarios of the game automatically many times:
  1. The player starts with a random choice and then decides **not** to change the choice. 
  1. The player starts with a random choice and then decides to change the choice. 
  
  Estimate the probability of winning the game in both scenarios using your results. Which of the two strategies is better?

In [35]:
# write your code here
n = 10000

scenario_1 = []
scenario_2 = []

for i in range(n):
    scenario_1.append(monthy_hall(start_choice=random.choice([1,2,3]),
                                  change_choice='no', verbose=False))
    
for i in range(n):
    scenario_2.append(monthy_hall(start_choice=random.choice([1,2,3]),
                                  change_choice='yes', verbose=False))

In [36]:
print(f"The probability to win in the first scenario is {sum(scenario_1)/n*100:.2f}%.")
print(f"The probability to win in the second scenario is {sum(scenario_2)/n*100:.2f}%.")

The probability to win in the first scenario is 33.18%.
The probability to win in the second scenario is 67.13%.


# Data types in Python

In [37]:
a = 10 # python recognizes types automatically when you initialize a variable

In [38]:
type(a)

int

In [39]:
a = 10.

In [40]:
type(a)

float

In [41]:
a = True

In [42]:
type(a)

bool

In [43]:
a = 'Hello world!'

In [44]:
type(a)

str

In [45]:
a = None

In [46]:
type(a)

NoneType

# Data structures (containers) in Python

**tuple**

In [47]:
a = (1,'cat',True) # tuple is a fixed-length sequence of any Python types

In [48]:
type(a)

tuple

In [49]:
a[1] = '1' # tuple is immutable! (cannot be changed)

TypeError: 'tuple' object does not support item assignment

In [50]:
a1, a2, a3 = a # tuple can be "unpacked"

a2

'cat'

In [51]:
(a1, a2, a3) = (a3, a1, a2) # using tuple, we can swap variables

a2

1

In [52]:
a1, a2, a3 = a3, a1, a2 # you can also omit brackets

**list**

In [53]:
a = [1,'cat',True] # list is also a fixed-length sequence of any Python types

In [54]:
type(a)

list

In [55]:
a[0] = 2 # lists are mutable! (can be changed)

a

[2, 'cat', True]

In [56]:
a.append(1) # add an element

a

[2, 'cat', True, 1]

In [57]:
a.extend([2,3,4]) # add several elements 

a

[2, 'cat', True, 1, 2, 3, 4]

In [58]:
a.pop() # remove last element

a

[2, 'cat', True, 1, 2, 3]

In [59]:
a.remove('cat') # remove element by value

a

[2, True, 1, 2, 3]

In [60]:
2 in a #check membership

True

In [61]:
'cat' in a

False

In [62]:
a = [1,8,5,3,12,2,4]
a.sort() #sort list in place

a

[1, 2, 3, 4, 5, 8, 12]

In [63]:
a[1:6] #slicing

[2, 3, 4, 5, 8]

In [64]:
a[1:6:2] #slicing with step 2

[2, 4, 8]

In [65]:
a[-3:-1]

[5, 8]

In [66]:
a[::-1] #reverse array

# the same indexing and slicing will also work for tuple, str 
# or other sequence types

[12, 8, 5, 4, 3, 2, 1]

**dictionary**

In [67]:
a = {'key1': 'val1',  # dictionary is a set of key-value pairs
     'key2': 2 ,
     1: 3}

In [68]:
type(a)

dict

In [69]:
a.keys() # extract keys

dict_keys(['key1', 'key2', 1])

In [70]:
a.values() # extract values

dict_values(['val1', 2, 3])

In [71]:
a['key1'] # doctionary can be indexed by keys
          # note that dictionaries are otherwise unordered

'val1'

In [72]:
a[2]

KeyError: 2

In [73]:
a[2] = 'new_val' # you can a new key-value pair like this

a

{'key1': 'val1', 'key2': 2, 1: 3, 2: 'new_val'}

In [74]:
'key1' in a # you can check whether a key is in the dictionary

True

**set**

In [75]:
a = set([0,1,2,2,2,3,3,4,5]) # set is an unordered and contains unique elements

In [76]:
type(a)

set

In [77]:
a

{0, 1, 2, 3, 4, 5}

In [78]:
a[1] # since sets are unordered, you cannot index them!

TypeError: 'set' object is not subscriptable

In [79]:
3 in a # check if element is in the set

True

In [80]:
b = set([-3,-2,-1,0])

In [81]:
a & b # set intersection

{0}

In [82]:
a | b # set union

{-3, -2, -1, 0, 1, 2, 3, 4, 5}

In [83]:
a - b # set difference

{1, 2, 3, 4, 5}

In [84]:
a ^ b # xor

{-3, -2, -1, 1, 2, 3, 4, 5}

# If/else operators

In [85]:
a = [1,2,3]

if 2 in a:
    print('hello')

if 5 in a:
    print('hello')

hello


In [86]:
if (2 in a) and (3 in a):
    print('hello')

hello


In [87]:
if not((2 in a) and (3 in a)):
    print('hello')

In [88]:
if (5 in a) or (3 in a):
    print('hello')

hello


# Cycles and iterators

In [89]:
for i in [1,2,5]: # Python cycles can be over any iterable object (e.g. list, tuple, dictionary, string)
    print(i)

1
2
5


Technically, an **iterable** is any object that has method ``__iter__()``, which creates an **iterator**. Iterator is an object that has method ``__next__()``, which returns the next element of the iterable object or ``StopIteration`` exception when no more elements are available.

In [90]:
a = [1,2,3]

a_iterator = a.__iter__()

In [91]:
a_iterator.__next__()

1

In [92]:
a = range(1,10,2) # range is an iterable that only stores start, end and step values

type(a)

range

In [93]:
list(a)

[1, 3, 5, 7, 9]

In [94]:
for i in range(5):
    print(i)

0
1
2
3
4


In [95]:
for i in 'banana': #string is also an iterable
    print(i)

b
a
n
a
n
a


In [96]:
list(zip([1,2,3],[3,2,1])) # built-in zip function 

[(1, 3), (2, 2), (3, 1)]

In [97]:
for i,j,k in zip([1,2,3],[3,2,1],[2,1,3]):
    print(i,j,k)

1 3 2
2 2 1
3 1 3


In [98]:
list(enumerate(['a','b','c'])) # built-in enumerate function

[(0, 'a'), (1, 'b'), (2, 'c')]

In [99]:
for i,val in enumerate(['a','b','c']):
    print(i,val)

0 a
1 b
2 c
